import { FaAngleUp } from "react-icons/fa6";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';

import requestConfig from "../i18n/request";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",

  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mawarid",
  description: "Generated by create next app",
icons: {
       icon: '/Mawarid.png',
     }
};

export default async function RootLayout({ children, params }:any) {
 const { locale } = await params;
   const resolvedLocale = locale ?? "ar";
   const isRtl = ["ar"].includes(resolvedLocale);
 
   const messages = await requestConfig({
     requestLocale: Promise.resolve(resolvedLocale),
   });

  return (
    <html lang={locale} >
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div dir={isRtl ? "rtl" : "ltr"}></div>
       <main>{children}</main>
       <a id="totop" href="#top" className="top-visible">
        <i><FaAngleUp /></i>
    </a>
   
    <a id="chat" className="chat" href="https://wa.me/966920027202" target="_blank">
        <img src="	https://mawarid.com.sa/assets/images/whatsapp2%20(1).png" alt="whatsapp"/>
    </a>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
